#!/usr/bin/env python3
from __future__ import annotations

"""Create annotated parser-audit PDFs for a random subset of parsed PDF records."""

import argparse
import json
from pathlib import Path
import random
import sys
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.ingestion.parsing.pdf_audit import annotate_pdf_with_chunks


def build_args() -> argparse.Namespace:
    """Define and parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Recreate random original PDFs with parser hierarchy/chunk annotations."
    )
    parser.add_argument(
        "--parsed-jsonl",
        default="data/parsed/parsed_documents.jsonl",
        help="Parsed documents JSONL generated by parse_corpus.py.",
    )
    parser.add_argument(
        "--count",
        type=int,
        required=True,
        help="Number of random PDF records to annotate.",
    )
    parser.add_argument(
        "--output-dir",
        default="/volume1/Temp",
        help="Directory where annotated PDFs are written.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Optional random seed for reproducible selection.",
    )
    parser.add_argument(
        "--max-lines-per-note",
        type=int,
        default=18,
        help="Maximum hierarchy lines per annotation note.",
    )
    parser.add_argument(
        "--max-labels-per-page",
        type=int,
        default=0,
        help="Maximum red-framed chunk labels per page (0 = all that fit).",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing annotated output files.",
    )
    return parser.parse_args()


def load_pdf_rows(parsed_jsonl: str | Path) -> list[dict[str, Any]]:
    """Load parsed JSONL rows and keep only PDF-backed records."""
    path = Path(parsed_jsonl)
    if not path.exists():
        raise FileNotFoundError(f"Parsed JSONL not found: {path}")

    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_no, line in enumerate(handle, start=1):
            raw = line.strip()
            if not raw:
                continue
            try:
                row = json.loads(raw)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON at line {line_no} in {path}") from exc
            if not isinstance(row, dict):
                continue
            metadata = row.get("metadata", {})
            if not isinstance(metadata, dict):
                continue
            if str(metadata.get("file_ext", "")).lower() != ".pdf":
                continue
            source_path = Path(str(metadata.get("source_path", "")))
            if not source_path.exists():
                continue
            rows.append(row)
    return rows


def output_path(output_dir: str | Path, doc_id: str) -> Path:
    """Build deterministic output file path for one document id."""
    return Path(output_dir) / f"{doc_id}.annotated.pdf"


def main() -> None:
    """Run batch random parser-audit PDF generation."""
    args = build_args()
    if args.count <= 0:
        raise SystemExit("--count must be greater than 0.")

    rows = load_pdf_rows(args.parsed_jsonl)
    available = len(rows)
    if available == 0:
        raise SystemExit("No eligible PDF records found in parsed JSONL.")
    if args.count > available:
        raise SystemExit(f"Requested --count={args.count}, but only {available} PDF records are available.")

    rng = random.Random(args.seed)
    selected_rows = rng.sample(rows, args.count)

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    generated = 0
    for row in selected_rows:
        doc_id = str(row.get("doc_id", ""))
        metadata = row.get("metadata", {}) if isinstance(row.get("metadata"), dict) else {}
        source_pdf = Path(str(metadata.get("source_path", "")))
        relative_path = str(metadata.get("relative_path", ""))
        child_nodes = tuple(item for item in row.get("child_nodes", []) if isinstance(item, dict))
        parent_nodes = tuple(item for item in row.get("parent_nodes", []) if isinstance(item, dict))
        elements = tuple(item for item in row.get("elements", []) if isinstance(item, dict))

        if not doc_id or not source_pdf.exists():
            continue

        target = output_path(out_dir, doc_id)
        if target.exists() and not args.overwrite:
            print(f"SKIP (exists): {target}")
            continue

        annotate_pdf_with_chunks(
            source_pdf=source_pdf,
            output_pdf=target,
            doc_id=doc_id,
            relative_path=relative_path,
            parent_nodes=parent_nodes,
            child_nodes=child_nodes,
            elements=elements,
            max_lines_per_note=args.max_lines_per_note,
            max_labels_per_page=(None if args.max_labels_per_page == 0 else args.max_labels_per_page),
        )
        generated += 1
        print(f"OK: {target}")

    print(f"Generated: {generated}")
    print(f"Requested: {args.count}")
    print(f"Output dir: {out_dir}")


if __name__ == "__main__":
    main()
