#!/usr/bin/env python3
from __future__ import annotations

"""Create an annotated PDF showing parsed chunks, hierarchy, and labels."""

import argparse
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.ingestion.parsing.pdf_audit import annotate_pdf_with_chunks, load_parsed_record


def build_args() -> argparse.Namespace:
    """Define and parse CLI arguments."""
    parser = argparse.ArgumentParser(description="Annotate one source PDF with parsed chunk labels/hierarchy.")
    parser.add_argument(
        "--parsed-jsonl",
        default="data/parsed/parsed_documents.jsonl",
        help="Parsed documents JSONL generated by parse_corpus.py.",
    )
    parser.add_argument("--doc-id", default=None, help="Document id selector.")
    parser.add_argument("--relative-path", default=None, help="Relative path selector.")
    parser.add_argument("--source-pdf", default=None, help="Absolute source PDF path selector.")
    parser.add_argument(
        "--output-pdf",
        default="data/parsed/annotated_parser_audit.pdf",
        help="Destination path for annotated PDF output.",
    )
    parser.add_argument(
        "--max-lines-per-note",
        type=int,
        default=14,
        help="Maximum chunk lines in one annotation note before splitting.",
    )
    parser.add_argument(
        "--max-labels-per-page",
        type=int,
        default=0,
        help="Maximum red-framed chunk labels per page (0 = all that fit).",
    )
    return parser.parse_args()


def main() -> None:
    """Resolve one parsed record and write annotated PDF."""
    args = build_args()
    selectors = [args.doc_id, args.relative_path, args.source_pdf]
    if sum(value is not None for value in selectors) != 1:
        raise SystemExit("Provide exactly one selector: --doc-id OR --relative-path OR --source-pdf.")

    record = load_parsed_record(
        args.parsed_jsonl,
        doc_id=args.doc_id,
        relative_path=args.relative_path,
        source_pdf=args.source_pdf,
    )

    source_pdf_path = Path(record.source_path)
    if source_pdf_path.suffix.lower() != ".pdf":
        raise SystemExit(
            f"Selected record is not a PDF source ({record.source_path}). "
            "Use a parsed record that came from a .pdf file."
        )

    annotate_pdf_with_chunks(
        source_pdf=source_pdf_path,
        output_pdf=args.output_pdf,
        doc_id=record.doc_id,
        relative_path=record.relative_path,
        parent_nodes=record.parent_nodes,
        child_nodes=record.child_nodes,
        elements=record.elements,
        max_lines_per_note=args.max_lines_per_note,
        max_labels_per_page=(None if args.max_labels_per_page == 0 else args.max_labels_per_page),
    )
    print(f"Annotated PDF written to: {args.output_pdf}")
    print(f"doc_id: {record.doc_id}")
    print(f"source_pdf: {record.source_path}")
    print(f"child_chunks: {len(record.child_nodes)}")


if __name__ == "__main__":
    main()
