#!/usr/bin/env python3
"""Create annotated parser-audit PDFs for a random subset of parsed PDF records."""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path
from typing import Any

from src.ingestion.parsing.pdf_audit import annotate_pdf_with_chunks


def build_args() -> argparse.Namespace:
    """Define and parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Recreate random original PDFs with parser hierarchy/chunk annotations."
    )
    parser.add_argument(
        "--parsed-jsonl",
        default="data/parsed/parsed_documents.jsonl",
        help="Parsed documents JSONL generated by parse_corpus.py.",
    )
    parser.add_argument(
        "--count",
        type=int,
        required=True,
        help="Number of random PDF records to annotate.",
    )
    parser.add_argument(
        "--output-dir",
        default="/volume1/Temp",
        help="Directory where annotated PDFs are written.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Optional random seed for reproducible selection.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing annotated output files.",
    )
    return parser.parse_args()


def load_pdf_rows(parsed_jsonl: str | Path) -> list[dict[str, Any]]:
    """Load parsed JSONL rows and keep only PDF-backed records."""
    path = Path(parsed_jsonl)
    if not path.exists():
        raise FileNotFoundError(f"Parsed JSONL not found: {path}")

    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_no, line in enumerate(handle, start=1):
            raw = line.strip()
            if not raw:
                continue
            try:
                row = json.loads(raw)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON at line {line_no} in {path}") from exc
            if not isinstance(row, dict):
                continue
            metadata = row.get("metadata", {})
            if not isinstance(metadata, dict):
                continue
            if str(metadata.get("file_ext", "")).lower() != ".pdf":
                continue
            source_path = Path(str(metadata.get("source_path", "")))
            if not source_path.exists():
                continue
            rows.append(row)
    return rows


def output_path(output_dir: str | Path, ordinal: int) -> Path:
    """Build deterministic output file path for one sampled record index."""
    if ordinal <= 0:
        raise ValueError("ordinal must be greater than 0.")
    return Path(output_dir) / f"{ordinal}.pdf"


def main() -> None:
    """Run batch random parser-audit PDF generation."""
    args = build_args()
    if args.count <= 0:
        raise SystemExit("--count must be greater than 0.")

    rows = load_pdf_rows(args.parsed_jsonl)
    available = len(rows)
    if available == 0:
        raise SystemExit("No eligible PDF records found in parsed JSONL.")
    if args.count > available:
        raise SystemExit(
            f"Requested --count={args.count}, but only {available} PDF records are available."
        )

    rng = random.Random(args.seed)
    selected_rows = rng.sample(rows, args.count)

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    generated = 0
    for ordinal, row in enumerate(selected_rows, start=1):
        metadata = row.get("metadata", {}) if isinstance(row.get("metadata"), dict) else {}
        source_pdf = Path(str(metadata.get("source_path", "")))
        relative_path = str(metadata.get("relative_path", ""))
        elements = tuple(item for item in row.get("elements", []) if isinstance(item, dict))

        if not source_pdf.exists():
            continue

        target = output_path(out_dir, ordinal)
        if target.exists() and not args.overwrite:
            print(f"SKIP (exists): {target}")
            continue

        annotate_pdf_with_chunks(
            source_pdf=source_pdf,
            output_pdf=target,
            relative_path=relative_path,
            elements=elements,
        )
        generated += 1
        print(f"OK: {target}")

    print(f"Generated: {generated}")
    print(f"Requested: {args.count}")
    print(f"Output dir: {out_dir}")


if __name__ == "__main__":
    main()
